from ontology.models import DataQualityFindings, DatasetVerdict, SchemaEvaluationFindings


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def _issue_rows(findings: DataQualityFindings) -> list[str]:
    rows = []
    for issue in findings.anomalies[:10]:
        scope = issue.affected_column or "dataset"
        rows.append(
            f"| {issue.severity.value} | {issue.issue_type} | {scope} | "
            f"{issue.affected_count} ({_pct(issue.affected_percent)}) | {issue.description} |"
        )
    return rows


def _schema_rows(schema: SchemaEvaluationFindings | None) -> list[str]:
    if schema is None:
        return []
    rows = []
    for issue in schema.integrity_errors[:10]:
        scope = issue.affected_column or issue.affected_table
        rows.append(
            f"| {issue.severity.value} | {issue.error_type} | {scope} | {issue.description} |"
        )
    return rows


def render_markdown_report(
    findings: DataQualityFindings | None,
    verdict: DatasetVerdict,
    schema: SchemaEvaluationFindings | None = None,
) -> str:
    meta = verdict.dataset_meta
    lines = [
        "# Smart EDA Summary Report",
        "",
        f"## Verdict: {verdict.verdict.value}",
        "",
        verdict.verdict_rationale,
        "",
        "## Dataset",
        "",
        f"- File: `{meta.file_name}`",
        f"- Rows: {meta.n}",
        f"- Columns: {meta.n_var}",
        f"- Missing cells: {_pct(meta.p_cells_missing)}",
        f"- Duplicate rows: {meta.n_duplicates} ({_pct(meta.p_duplicates)})",
        "",
    ]

    if findings is not None:
        lines.extend([
            "## Data Quality Findings",
            "",
            "| Severity | Type | Scope | Affected | Explanation |",
            "| --- | --- | --- | --- | --- |",
        ])
        rows = _issue_rows(findings)
        lines.extend(rows or ["| INFO | NONE | dataset | 0 (0.0%) | No data quality issue emitted. |"])
        lines.append("")

    schema_rows = _schema_rows(schema)
    if schema is not None:
        lines.extend([
            "## Schema And Relationship Findings",
            "",
            "| Severity | Type | Scope | Explanation |",
            "| --- | --- | --- | --- |",
        ])
        lines.extend(schema_rows or ["| INFO | NONE | schema | No schema issue emitted. |"])
        lines.append("")

        if schema.relationships:
            lines.extend([
                "## Table Relationships",
                "",
                "| Type | Status | Relationship | Confidence | Evidence |",
                "| --- | --- | --- | --- | --- |",
            ])
            for rel in schema.relationships[:10]:
                relationship = (
                    f"{rel.child_table}.{rel.child_column} -> "
                    f"{rel.parent_table}.{rel.parent_column}"
                )
                evidence = "; ".join(rel.evidence)
                lines.append(
                    f"| {rel.relationship_type} | {rel.status} | {relationship} | "
                    f"{rel.confidence:.2f} | {evidence} |"
                )
            lines.append("")

    lines.extend([
        "## Severity Note",
        "",
        "Severity is generated by deterministic rules and the current calibrator config. "
        "The v0.1 thresholds are heuristic defaults and should be benchmark-calibrated "
        "before they are treated as scientifically validated risk scores.",
        "",
    ])
    return "\n".join(lines)
